### PR TITLE
Add Github information to Kabanero document for CLI

### PR DESCRIPTION
**Pull request by kaczyns**
This PR does the following:
- Exports several environment variables to the CLI pod 
- Generates the AES encryption key used by the CLI pod
- Updates the CLI container image to `kabanero/kabanero-command-line-services:0.1.1-rc.1`

This is essentially the setup described here:
https://github.com/kabanero-io/kabanero-security/wiki/Setting-up-the-CLI-backend-app

The operator now does all of these steps automatically.  The Kabanero document has changed by adding this piece, which is currently optional:
```yaml
spec:
  github:
    apiUrl: 'https://api.github.com'
    organization: kabanero-io
    teams:
      - adminTeam
```

If any of the pieces in `github` are present, the related environment variables will be created and set in the CLI pod:
```yaml
spec:
  containers:
    - env:
        - name: KABANERO_CLI_NAMESPACE
          value: kabanero
        - name: KABANERO_CLI_GROUP
          value: kabanero-io
        - name: teamsInGroup_admin
          value: adminTeam@kabanero-io
        - name: KABANERO_GITHUB_API_URL
          value: 'https://api.github.com'
        - name: AESEncryptionKey
          valueFrom:
            secretKeyRef:
              name: kabanero-cli-aes-encryption-key-secret
              key: AESEncryptionKey
              optional: false
```

I moved the code that creates a `Deployment` into its own part (from the landing page) and re-used it here.  I've also re-used the create owner reference code.  Some refactoring has already been suggested in PR #143, and that has not been done yet.

### CODE REVIEW

**Comment by kaczyns** [comment]
This PR fixes the following issues:
#138 
#136

**Comment by davco01a** [comment]
what about collection (repository) URL ?  I know you already have that covered, I see it in the Kab object, but is that exposed to `Todd` so he can alter it to point to the cloned master collection that champ will be curating?

**Comment by kaczyns** [comment]
@davco01a I'm not sure what you mean by "is that exposed to Todd"... any Kube admin can edit any part of the `Kabanero` document

**Comment by davco01a** [comment]
GIT hub api url eventually has to populate this environment variable for the microservice security code: `github.api.url`

**Pull request merged**
