### PR TITLE
tektoncd dashboard v0.6.1.4

### PR DESCRIPTION
**Pull request by dacleyra**
Pending status of v0.6.1.4 release
https://github.com/tektoncd/dashboard/releases

### CODE REVIEW

**Comment by anneqm** [comment]
Can we consider adding this statement? 
add an extra command to address extended time (per instructions [here](https://github.com/tektoncd/experimental/blob/c74ba9eadbeb61a8c2a00dbd5ca5d8a979e4165c/webhooks-extension/docs/InstallPrereqs.md)):
```
  oc annotate route tekton-dashboard --overwrite haproxy.router.openshift.io/timeout=2m
```
as mentioned in https://github.ibm.com/IBMCloudPak4Apps/icpa-system-test/issues/453.

**Comment by anneqm** [comment]
@kaczyns @dacleyra Did this one get in?

**Comment by dacleyra** [comment]
@anneqm no, this one is still pending

**Comment by anneqm** [comment]
Created SVT issue to track for Kabanero 0.9.1... https://github.ibm.com/IBMCloudPak4Apps/icpa-system-test/issues/605. Of course, between now and when this is merged, there is the potential for a svt bug fix.   Thanks all!

**Comment by anneqm** [comment]
@kaczyns Thank you!   did this one get picked up in kabanero 0.9+?

**Pull request merged**
