### PR TITLE
Add GrafanaDashboard, Secret and ConfigMap to pipeline ClusterRole, fix others

### PR DESCRIPTION
**Pull request by ianpartridge**
cc: @kvijai82

### CODE REVIEW

**Comment by ianpartridge** [comment]
@kvijai82 why do some of the `resources` in this ClusterRole specify the plural name (`appsodyapplications`, `serviceBindingRequests`) and some specify the singular name (`serviceMonitor`, `database`)?  Does it matter?

**Comment by kvijai82** [comment]
@ianpartridge that's the change I am trying to test out with Terrance today and will be creating a PR for.  It does matter.

**Comment by ianpartridge** [comment]
If it matters, do they have to be singular or plural?  I would guess plural, because that's what we had for the existing resources (`appsodyapplications`, `openlibertyapplications`).  If I'm correct, I guess that means I should update this PR to say grafanaDashboards?

**Comment by ianpartridge** [comment]
I saw that the CR you sent @tnixa was plural, so I've updated this PR accordingly. Hope that's correct.

**Comment by ianpartridge** [comment]
Also added `Secret` and `ConfigMap` as two core resources we expect users will want to include in their GitOps repo. `Secret` is definitely required in order to get OpenLiberty metrics working (because the `/metrics` endpoint requires authentication).

**Pull request merged**
