### PR TITLE
Remove v1alpha1 CRDs and related bits

### PR DESCRIPTION
**Pull request by dacleyra**

### CODE REVIEW

**Comment by kaczyns** [comment]
This looks good Dan.  I didn't see anything that would delete the collection controller deployment and friends on an upgrade from 0.9.0 to 0.10.0.  I think we need something in the kabanero controller that makes sure the collections stuff is deleted (deployment/pod, SA, roles, etc).  I'm not sure that stuff would get deleted on an upgrade unless the Kab CR instance was deleted.  Do you agree?
@dacleyra

**Comment by dacleyra** [comment]
Maybe. The upgrade scenario doesn't satisfy InstallPlan

```
    Message:               error missing existing CRD version(s) in new CRD: kabaneros.kabanero.io: New CRD (kabaneros.kabanero.io) must contain existing served versions
(v1alpha1)
```

https://github.com/operator-framework/operator-lifecycle-manager/blob/fb2879e6ec1f54973f69a2d6136fc99094e2b261/doc/design/dependency-resolution.md#deprecateremove-a-version-of-crd

I don't think we set v1alpha1 served: false in a version previous

**Comment by kaczyns** [comment]
Do we just need to introduce an artificial step (like have 0.9.1 set served = false for v1alpha1 and then 0.10.0 can remove it)?

**Comment by dacleyra** [comment]
yes

**Comment by dacleyra** [comment]
Setting served = false in 0.9.1, and then installing 0.10.0 from the PR worked
InstallPlan was successful
collection controller deployment is gone
the collections CRD sticks around though, but that seems to be normal? I don't think OLM necessarily cleans out CRDs

**Comment by dacleyra** [comment]
close in favor of 
https://github.com/kabanero-io/kabanero-operator/pull/760

**Pull request closed without merging**
